# Generated by Django 4.1.10 on 2023-08-26 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PumpHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=12)),
                ('code', models.CharField(max_length=10)),
                ('pump_no', models.CharField(max_length=2)),
                ('latitude', models.CharField(blank=True, max_length=12)),
                ('longitude', models.CharField(blank=True, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='PumpLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running_hrs', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pumphouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pumpstation.pumphouse')),
            ],
        ),
        migrations.AddConstraint(
            model_name='pumphouse',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_pump_code'),
        ),
    ]
