# Generated by Django 4.1.10 on 2023-08-30 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pumpstation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pumphouse',
            old_name='location',
            new_name='name',
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('latitude', models.CharField(blank=True, max_length=12)),
                ('longitude', models.CharField(blank=True, max_length=12)),
                ('pumphouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pumpstation.pumphouse')),
            ],
        ),
    ]
