# Generated by Django 4.1.10 on 2023-08-30 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pumpstation', '0002_rename_location_pumphouse_name_pump'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pumphouse',
            name='unique_pump_code',
        ),
        migrations.RemoveField(
            model_name='pumphouse',
            name='code',
        ),
        migrations.RemoveField(
            model_name='pumphouse',
            name='pump_no',
        ),
    ]
