# Generated by Django 4.1.10 on 2023-08-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumpstation', '0003_remove_pumphouse_unique_pump_code_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pumphouse',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_pumphouse'),
        ),
    ]
