# Generated by Django 4.1.10 on 2023-09-01 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pumpstation', '0004_pumphouse_unique_pumphouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pumplog',
            name='pumphouse',
        ),
        migrations.AddField(
            model_name='pumplog',
            name='pump',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pumpstation.pump'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='pump',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_pump'),
        ),
    ]
