# Generated by Django 4.1.10 on 2023-09-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumpstation', '0005_remove_pumplog_pumphouse_pumplog_pump_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pumplog',
            name='running_hrs',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
