# Generated by Django 4.1.10 on 2023-07-14 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=10)),
                ('conveyor_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NavMainMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=100, unique=True, verbose_name='Menu Name')),
                ('menu_id', models.CharField(default='', max_length=100, verbose_name='Menu ID')),
                ('icon', models.CharField(default='', max_length=100, verbose_name='Icon Name')),
                ('position', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name_plural': 'Main_menu',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=100, verbose_name='Vehicle Number')),
                ('trailer_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Trailer Number')),
                ('bp_name', models.CharField(max_length=100, verbose_name='Business Partner Name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('has_order', models.BooleanField(default=False, verbose_name='Order')),
                ('has_order_time', models.DateTimeField(blank=True, null=True)),
                ('loaded', models.BooleanField(default=False, verbose_name='Loaded')),
                ('loaded_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeightCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NavSubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_menu_name', models.CharField(max_length=100, verbose_name='Submenu Name')),
                ('application_name', models.CharField(default='', max_length=50, verbose_name='App Name')),
                ('url', models.CharField(default='#', max_length=100, verbose_name='Url')),
                ('position', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('navmainmenu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbmaster.navmainmenu')),
            ],
            options={
                'verbose_name_plural': 'Sub_menu',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('port', models.IntegerField()),
                ('location', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='dbmaster.location')),
            ],
        ),
    ]
