# Generated by Django 4.1.10 on 2023-08-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coa',
            name='batch_no',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='historicalcoa',
            name='batch_no',
            field=models.CharField(max_length=7),
        ),
    ]
