# Generated by Django 4.1.10 on 2023-07-14 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dbmaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=8)),
                ('quantity', models.IntegerField()),
                ('is_loaded', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LoadingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=30)),
                ('bag_cnt', models.IntegerField()),
                ('device', models.CharField(max_length=15)),
                ('order', models.CharField(max_length=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbmaster.weightcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_50', models.IntegerField(default=0)),
                ('order_25', models.IntegerField(default=0)),
                ('order_20', models.IntegerField(default=0)),
                ('order_6', models.IntegerField(default=0)),
                ('is_running', models.BooleanField()),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='dbmaster.device')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='dbmaster.ticket')),
            ],
        ),
        migrations.AddConstraint(
            model_name='counter',
            constraint=models.UniqueConstraint(fields=('device',), name='unique counter device'),
        ),
    ]
