# Generated by Django 4.1.10 on 2023-07-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='counter',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
    ]
