# Generated by Django 4.1.10 on 2023-07-17 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmaster', '0001_initial'),
        ('sales', '0003_remove_counter_unique counter device'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_no', models.IntegerField()),
                ('loaded_quantity', models.IntegerField(blank=True)),
                ('cnt_50', models.IntegerField()),
                ('cnt_25', models.IntegerField()),
                ('cnt_20', models.IntegerField()),
                ('cnt_6', models.IntegerField()),
                ('close_order_time', models.DateTimeField(blank=True, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbmaster.ticket')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AlterField(
            model_name='counter',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbmaster.device'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbmaster.ticket'),
        ),
    ]
